apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: new-disk-claim
  namespace: default
spec:
  resources:
    requests: 
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
