apiVersion: v1
kind: Pod
metadata:
  name: data-transfer-pod
  namespace: default
spec:
  containers:
  - name: data-transfer-container
    image: nginx
    volumeMounts:
    - mountPath: /temp
      name: script-data
  volumes:
  - name: script-data
    persistentVolumeClaim:
      claimName: new-disk-claim 